Add some common shuffles
rust-lang/stdsimd pull request #98
Opened 2021-04-17 18:19 UTC by calebzulawski

Skipping `rotate` etc right now, since it depends on some more const eval that we don't have.

2021-04-17 19:04 UTC, workingjubilee requested changes
Ahaha, I love it.

I agree with adding these operations.
It would be nice to prove they are optimized on aarch64 or even on x86_64 before we stabilize these, but I will leave that thought for future "verify vectorization" efforts.

We do need to unfortunately be agonizingly clear as to what ordering is gained from these ops, though.

`fn reverse` seems fine. I could see bikeshedding over `fn interleave`, (mostly because `deinterleave` seems verbose) but eh, the name seems fine, really! Just needs clear docs, is all.

2021-04-17 19:18 UTC, calebzulawski commented
`interleave` and `deinterleave` could certainly be `zip` and `unzip` (like the arm instruction names).  Intel uses `pack` and `unpack` which I'm not a fan of.  My only concern was that `zip` could get confused with iterator zipping (though it's fairly similar, I guess?)

2021-04-17 19:20 UTC, calebzulawski commented on crates/core_simd/src/permute.rs
> +            pub fn interleave(self, other: Self) -> (Self, Self) {
Yeah, I agree that all of those definitions are a little vague.  There's probably a clearer way to describe it, but I'm not sure what that is.

2021-04-21 06:24 UTC, workingjubilee approved these changes

2021-04-21 06:32 UTC, workingjubilee commented
This looks much better now.
I agree that "pack" and "unpack" is really... unfitting, and that zip/unzip risks some confusion.

2021-04-21 06:33 UTC, merged